FROM "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye"

LABEL name="Angular dev environment" \
      description="This image can be used to create a dev environment for building Angular." \
      vendor="angular" \
      version="1.0"

EXPOSE 8100 8200

